commands:
- description: Generate a post for a specific platform
  name: generate-post
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/generate-devto-post.md.jinja2
    model: gpt-4o
    snap: false
    spinner: true
    sync: true
    verbose: true
    wait: true
- description: Answer a few questions and create a new draft
  name: draft
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/draft-post.md.jinja2
    model: gpt-4o
    snap: false
    spinner: true
    sync: true
    verbose: true
    wait: true
- description: Generate PR Title & Description
  name: pr-description
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/generate-pr-description.md.jinja2
    model: gpt-4o
    snap: false
    spinner: false
    sync: false
    verbose: false
    wait: true
- description: Make changes to a post
  name: edit-post
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/edit-post.md.jinja2
    model: gpt-4o
    snap: false
    spinner: true
    sync: true
    verbose: true
    wait: true
- description: Write content for distributing a post on social media
  name: distribute
  params:
    cheap: false
    code: false
    debug: false
    direct: false
    file: prompts/distribute.md.jinja2
    model: gpt-4o
    snap: false
    spinner: true
    sync: true
    verbose: true
    wait: true
